---
- name: Converge
  hosts: all
  tasks:
    - command:
        cmd: id
      register: _id_cmd
    - debug:
        msg: |
          inventory_hostname : {{ inventory_hostname }}
          ansible_host : {{ ansible_host }}
          id : {{ _id_cmd.stdout }}

    - name: "Run bootstrap pre tasks"
      ansible.builtin.import_role:
        name: wandansible.bootstrap
        tasks_from: pre
      vars:
        bootstrap_host_override_prompt: false
        bootstrap_username: root
        bootstrap_password: root
        bootstrap_become_method: sudo
        bootstrap_ssh_password_authentication: false
        bootstrap_user_remove: false

    - name: Create user accounts and groups as provision user
      ansible.builtin.user:
        name: test
        uid: 1000
      vars:
        ansible_host: "{{ provision_host }}"
        ansible_user: "{{ provision_username }}"
        ansible_become_pass: "{{ provision_password }}"
        ansible_ssh_private_key_file: "{{ provision_ssh_private_key }}"

    - name: Run bootstrap post tasks
      ansible.builtin.import_role:
        name: wandansible.bootstrap
        tasks_from: post
      vars:
        ansible_host: "{{ provision_host }}"
