---
- name: Converge
  hosts: all
  tasks:
    - name: "Run bootstrap pre tasks"
      ansible.builtin.import_role:
        name: wandansible.bootstrap
        tasks_from: pre
      become: true
      vars:
        bootstrap_host_override_prompt: false
        bootstrap_username: ansible
        bootstrap_password: ansible
        bootstrap_become_method: sudo
        bootstrap_ssh_password_authentication: false
        bootstrap_user_remove: false

    - name: Create user accounts and groups as provision user
      ansible.builtin.user:
        name: test
      become: true
      vars:
        ansible_host: "{{ provision_host }}"
        ansible_user: "{{ provision_username }}"
        ansible_become_pass: "{{ provision_password }}"
        ansible_ssh_private_key_file: "{{ provision_ssh_private_key }}"

    - name: Run bootstrap post tasks
      ansible.builtin.import_role:
        name: wandansible.bootstrap
        tasks_from: post
      become: true
      vars:
        ansible_host: "{{ provision_host }}"
